// <auto-generated />
using System;
using AutomateDot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomateDot.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250717100458_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("AutomateDot.Data.Entities.AutomateExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AutomateRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutomateRecipeId");

                    b.ToTable("AutomateExecutions");
                });

            modelBuilder.Entity("AutomateDot.Data.Entities.AutomateExecutionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutomateExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutomateExecutionId");

                    b.ToTable("AutomateExecutionEntries");
                });

            modelBuilder.Entity("AutomateDot.Data.Entities.AutomateRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionConfiguration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerConfiguration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AutomateRecipes");
                });

            modelBuilder.Entity("AutomateDot.Data.Entities.AutomateExecution", b =>
                {
                    b.HasOne("AutomateDot.Data.Entities.AutomateRecipe", "AutomateRecipe")
                        .WithMany()
                        .HasForeignKey("AutomateRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomateRecipe");
                });

            modelBuilder.Entity("AutomateDot.Data.Entities.AutomateExecutionEntry", b =>
                {
                    b.HasOne("AutomateDot.Data.Entities.AutomateExecution", "AutomateExecution")
                        .WithMany("AutomateExecutionEntries")
                        .HasForeignKey("AutomateExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomateExecution");
                });

            modelBuilder.Entity("AutomateDot.Data.Entities.AutomateExecution", b =>
                {
                    b.Navigation("AutomateExecutionEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
