name: Dev Pipeline

on:
  push:
    branches:
      - dev  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build the solution
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
